# prettier-ignore
name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  material_design_icons_flutter: 7.0.7296
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
  - family: NotoSansJP
    fonts:
      - asset: fonts/NotoSansJP-Regular.ttf
      - asset: fonts/NotoSansJP-Bold.ttf
        weight: 700
      - asset: fonts/NotoSansJP-Thin.ttf
        weight: 100
      - asset: fonts/NotoSansJP-Light.ttf
        weight: 300
